version: "3.8"
services:
  mongodb:
    image: mongo
    hostname: "mongodb"
  
  wo-app:
    image: "yevgeniis/wo_app:0.1.0"
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      - MONGODB_ADDRESS=mongodb
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    
