apiVersion: cert-manager.io/v1                             
kind: ClusterIssuer                             
metadata:                               
  name: letsencrypt-cluster-issuer                             
spec:                            
  acme:                                 
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ####enter Here your email
    privateKeySecretRef:                                                                   
      name: letsencrypt-cluster-issuer-key
    solvers:
    - http01:
        ingress:
          class: nginx

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wo-app  #name of this object
  namespace: default #same namespace as 
spec:
  dnsNames:
    - api.xarfa.com
  secretName: wo-app-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
